Add support for Ollama (via openai compatible APIs)
baalimago/clai pull request #16
Opened 2024-07-14 19:24 UTC by raff

Use `-cm ollama` to select the default model (llama3) or `-cm ollama:{model}` to select a differnt model.
Ollama should be running locally on the default port `http://localhost:11434`

2024-07-15 16:46 UTC, baalimago requested changes
Looks good, and many thanks for the addition! One request though: could you please update the README.md with an entry similar to the other vendors?  I think a link that gives a brief start to get started with ollama plus the requirement of default ollama port.

Also, I don't have a beefy enough computer to run ollama myself, but I trust you've verified functionality yourself

2024-07-15 17:01 UTC, raff commented
Sure, I'll update the readme. And yes, I did verified myself (chat and query commands)

2024-07-15 17:14 UTC, baalimago requested changes
This also needs to get updated: [/baalimago/clai/blob/main/internal/text/querier_setup.go#L20](https://github.com/baalimago/clai/blob/main/internal/text/querier_setup.go#L20) in order to support the config system for the different models. Right now, I suspect the configuration file for any ollama model will overwrite each others at `<os-config-dir>/.clai/VENDOR_NOT_FOUND.json`. 

I think `<os-config-dir>/.clai/ollama_ollama_{model}` would be an appropriate format, with `{model}` being just `ollama` for the default case.

You can verify the problem+solution by checking out `<os-config-dir>/.clai/` (probably `~/.config/.clai`) or running `clai setup` -> 1 (model files) -> c (configure) and seeing `ollama_ollama_...` config files (and the lack thereof, until change)

EDIT: I think I'll refactor this so that this is inside the respective vendors, but I'll do so aftter this PR to make it less confusing

2024-08-15 17:43 UTC, baalimago commented
Hello! I'm planning on making a new minor release soon and I'd really like to have this PR in it. Do you have any progress on the suggested changes?

I also had a thought that we could just merge this as is, and I'll refactor as mentioned above. But since I don't have ollama myself, I'd appreciate if you'd run and verify that the configuration works as intended. Could this work?

2024-08-15 18:05 UTC, raff commented
Sorry for the delay. Let me test one more time. I'll let you know later
today.


On Thu, Aug 15, 2024 at 10:43 AM Lorentz Kinde ***@***.***>
wrote:

> Hello! I'm planning on making a new minor release soon and I'd really like
> to have this PR in it. Do you have any progress on the suggested changes?
>
> I also had a thought that we could just merge this as is, and I'll
> refactor as mentioned above. But since I don't have ollama myself, I'd
> appreciate if you'd run and verify that the configuration works as
> intended. Could this work?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/baalimago/clai/pull/16#issuecomment-2291840462>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAANESB4N6QQHKO2N3NGJODZRTSFPAVCNFSM6AAAAABK3MXCLSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJRHA2DANBWGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-19 17:17 UTC, baalimago commented
I'll proceed and merge this and do the refactor! If something doesn't work, please make an issue and I'll check it out, or submit another PR to fix it.

Thanks for your contributions!

2024-08-19 17:18 UTC, merged

2024-08-19 17:31 UTC, baalimago commented
I doublechecked my own suggested refactors and it didn't really make any sense, apologies for the confusion! I updated the readme,

2024-08-19 19:47 UTC, raff commented
Awesome, thanks!

On Mon, Aug 19, 2024 at 10:31 AM Lorentz Kinde ***@***.***>
wrote:

> I doublechecked my own suggested refactors and it didn't really make any
> sense, apologies for the confusion! I updated the readme,
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/baalimago/clai/pull/16#issuecomment-2297081680>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAANESAA3KLFXGEZC52CA73ZSITY7AVCNFSM6AAAAABK3MXCLSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJXGA4DCNRYGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-11-08 14:13 UTC, Diti commented
Hello, how is one supposed to use the Ollama integration? It isn’t documented AFAIK.

```shell
$ clai -chat-model ollama:deepseek-r1:8b query My favorite color is blue, tell me some facts about it
2025-11-08T15:13:13+01:00 error: failed to run: failed to stream completions: unexpected status code: 400 Bad Request, body: {"error":{"message":"model is required","type":"api_error","param":null,"code":null}}
```

2025-11-10 05:40 UTC, baalimago commented
@Diti Hmm, that's odd. I tried the same (but with `gemma3:1b`) and it seems to be working for me:
```bash
Terminal 1:
ollama run gemma3:1b

Terminal 2:
❯ clai -chat-model ollama:gemma3:1b query hello
system:
  Hello there! How can I help you today?
```

---
Could you please re-run the query with `DEBUG=1` and then show me the output? 
```bash
DEBUG=1 clai -chat-model ollama:deepseek-r1:8b query My favorite color is blue, tell me some facts about it
```

2025-11-10 11:36 UTC, Diti commented
Heya @baalimago, thank you for your support!

The output of the command with the `DEBUG` flag follows.

```
2025-11-10T12:20:04+01:00 ok: attempting to load file: /home/diti/.config/.clai/textConfig.json
2025-11-10T12:20:04+01:00 ok: found config: {
 "model": "gpt-5",
 "system-prompt": "You are an assistant for a CLI tool. Answer concisely and informatively. Prefer markdown if possible.",
 "cmd-mode-prompt": "You are an assistant for a CLI tool aiding with cli tool suggestions. Write ONLY the command and nothing else. Disregard any queries asking for anything except a bash command. Do not shell escape single or double quotes.",
 "raw": false,
 "use-tools": false,
 "token-warn-limit": 333333,
 "tool-output-rune-limit": 21600,
 "save-reply-as-prompt": true
}
2025-11-10T12:20:04+01:00 ok: config post flag override: {
 "model": "ollama:deepseek-r1:8b",
 "system-prompt": "You are an assistant for a CLI tool. Answer concisely and informatively. Prefer markdown if possible.",
 "cmd-mode-prompt": "You are an assistant for a CLI tool aiding with cli tool suggestions. Write ONLY the command and nothing else. Disregard any queries asking for anything except a bash command. Do not shell escape single or double quotes.",
 "raw": false,
 "use-tools": false,
 "token-warn-limit": 333333,
 "tool-output-rune-limit": 21600,
 "save-reply-as-prompt": true
}
2025-11-10T12:20:04+01:00 ok: stdinReplace:
2025-11-10T12:20:04+01:00 ok: InitialPrompt: {
 "created": "0001-01-01T00:00:00Z",
 "id": "",
 "messages": [
  {
   "role": "system",
   "content": "You are an assistant for a CLI tool. Answer concisely and informatively. Prefer markdown if possible."
  },
  {
   "role": "user",
   "content": "My favorite color is blue, tell me some facts about it"
  }
 ]
}
2025-11-10T12:20:04+01:00 ok: userConf: {
 "model": "ollama:deepseek-r1:8b",
 "system-prompt": "You are an assistant for a CLI tool. Answer concisely and informatively. Prefer markdown if possible.",
 "cmd-mode-prompt": "You are an assistant for a CLI tool aiding with cli tool suggestions. Write ONLY the command and nothing else. Disregard any queries asking for anything except a bash command. Do not shell escape single or double quotes.",
 "raw": false,
 "use-tools": false,
 "token-warn-limit": 333333,
 "tool-output-rune-limit": 21600,
 "save-reply-as-prompt": true
}
2025-11-10T12:20:04+01:00 ok: querier: {
 "URL": "",
 "Raw": false,
 "Model": {
  "model": "ollama:deepseek-r1:8b",
  "frequency_penalty": 0,
  "max_tokens": null,
  "presence_penalty": 0,
  "temperature": 1,
  "top_p": 1,
  "url": "https://api.deepseek.com/chat/completions"
 }
},
===
models: {
 "model": "ollama:deepseek-r1:8b",
 "frequency_penalty": 0,
 "max_tokens": null,
 "presence_penalty": 0,
 "temperature": 1,
 "top_p": 1,
 "url": "https://api.deepseek.com/chat/completions"
}
2025-11-10T12:20:04+01:00 ok: userConf: {
 "model": "ollama:deepseek-r1:8b",
 "system-prompt": "You are an assistant for a CLI tool. Answer concisely and informatively. Prefer markdown if possible.",
 "cmd-mode-prompt": "You are an assistant for a CLI tool aiding with cli tool suggestions. Write ONLY the command and nothing else. Disregard any queries asking for anything except a bash command. Do not shell escape single or double quotes.",
 "raw": false,
 "use-tools": false,
 "token-warn-limit": 333333,
 "tool-output-rune-limit": 21600,
 "save-reply-as-prompt": true
}
2025-11-10T12:20:04+01:00 ok: querier: {
 "URL": "",
 "Raw": false,
 "Model": {
  "model": "ollama:deepseek-r1:8b",
  "frequency_penalty": 0,
  "max_tokens": null,
  "presence_penalty": 0,
  "temperature": 1,
  "top_p": 1,
  "url": "https://api.deepseek.com/chat/completions"
 }
},
===
models: {
 "model": "ollama:deepseek-r1:8b",
 "frequency_penalty": 0,
 "max_tokens": null,
 "presence_penalty": 0,
 "temperature": 1,
 "top_p": 1,
 "url": "https://api.deepseek.com/chat/completions"
}
2025-11-10T12:20:04+01:00 ok: chat mode: false, type of querier: *text.Querier[*github.com/baalimago/clai/internal/vendors/ollama.Ollama]
2025-11-10T12:20:04+01:00 ok: querier post text querier create: {Model:ollama:deepseek-r1:8b SystemPrompt:You are an assistant for a CLI tool. Answer concisely and informatively. Prefer markdown if possible. CmdModePrompt:You are an assistant for a CLI tool aiding with cli tool suggestions. Write ONLY the command and nothing else. Disregard any queries asking for anything except a bash command. Do not shell escape single or double quotes. Raw:false UseTools:false TokenWarnLimit:333333 ToolOutputRuneLimit:21600 SaveReplyAsConv:true ConfigDir:/home/diti/.config/.clai StdinReplace: Stream:false ReplyMode:false ChatMode:false CmdMode:false Glob: InitialPrompt:{Created:0001-01-01 00:00:00 +0000 UTC ID:My_favorite_color_is_blue, Messages:[{Role:system Content:You are an assistant for a CLI tool. Answer concisely and informatively. Prefer markdown if possible. ToolCalls:[] ToolCallID:} {Role:user Content:My favorite color is blue, tell me some facts about it ToolCalls:[] ToolCallID:}]} UseProfile: ProfilePath: Tools:[] PostProccessedPrompt:My favorite color is blue, tell me some facts about it}
2025-11-10T12:20:04+01:00 ok: streamcompleter api key: ollama
2025-11-10T12:20:04+01:00 ok: generic streamcompleter request: {
 "model": "ollama:deepseek-r1:8b",
 "response_format": {
  "type": "text"
 },
 "messages": [
  {
   "role": "system",
   "content": "You are an assistant for a CLI tool. Answer concisely and informatively. Prefer markdown if possible."
  },
  {
   "role": "user",
   "content": "My favorite color is blue, tell me some facts about it"
  }
 ],
 "stream": true,
 "frequency_penalty": 0,
 "temperature": 1,
 "top_p": 1
}
2025-11-10T12:20:04+01:00 ok: {
 "Accept": [
  "text/event-stream"
 ],
 "Authorization": [
  "Bearer ollama"
 ],
 "Connection": [
  "keep-alive"
 ],
 "Content-Type": [
  "application/json"
 ]
}
2025-11-10T12:20:04+01:00 error: failed to run: failed to stream completions: unexpected status code: 400 Bad Request, body: {"error":{"message":"model is required","type":"api_error","param":null,"code":null}}
```

For your information, I packaged your Go project in my NixOS configuration like so.

```nix
(pkgs.buildGoModule rec {
  pname = "clai";
  version = "1.8.4";
  src = pkgs.fetchFromGitHub {
    owner = "baalimago";
    repo = "clai";
    rev = "v${version}";
    hash = "sha256-NOd86zCeq6jSeALZrjcPHwbNyxZtc9hRKR1ocI830tw=";
  };
  vendorHash = "sha256-J2EZY/Po+d6r0q57tYE2Wr9JoqLY5goRHV4kvCBPnDw=";
  nativeBuildInputs = [git];
  env = {
    # One of the tools wanted to write into `/homeless-shelter` during `checkPhase` for some reason.
    # Giving it temporary directories to make it happy – it uses my regular XDG directories at first run anyway.
    HOME = "/tmp";
    XDG_CONFIG_HOME = "/tmp/.config";
    XDG_DATA_HOME = "/tmp/.local/share";
  };
})
```
Using `ollama run deepseek-r1:8b My favorite color is blue, tell me some facts about it` works fine.

2025-11-10 17:28 UTC, baalimago commented
Ohh, it's attempting to use the deepseek remote API. I didn't take height for the deepseek models being used with ollama. 

I'll have fix ready shortly (a day or so) and tag you in PR @Diti .

2025-11-11 17:57 UTC, baalimago commented
Hello again @Diti,

I can't tag you from PR, but I made a PR here: https://github.com/baalimago/clai/pull/76

I've not yet been able to reproduce the issue, but did a minor cleanup which may fix it regardless. If nothing else,
debug logs using the branch in the PR might hone in on the issue.  Could we please continue the conversation there?