feat: add llm vendor Novita AI
baalimago/clai pull request #25
Opened 2024-10-31 07:01 UTC by jasonhp

Add new LLM vendor Novita AI

2024-10-31 16:02 UTC, baalimago requested changes
It looks good! Although, in its current state,  clai wont be able to instanciate the Novita struct. There's two steps missing:

1. [Here](https://github.com/baalimago/clai/blob/main/internal/create_queriers.go#L22) the default Novita querier needs to be created. This is what defines the type of the generic `models.Querier` interface, it also ensures that the custom configuration is created for the vendor + that the custom configurations for the specific models gets properly overwritten. 
2. [Here](https://github.com/baalimago/clai/blob/main/internal/text/querier_setup.go#L20) the vendor, model and model version needs to be parsed, also for the configuration system to work.

See how `ollama` is setup here for both steps. I'm thinking prefix `novita:` will work well.

So, if this is done right, I'm thinking it should be possible to run:
`clai -cm 'novita:gryphe/mythomax-l2-13b' query example123`

2024-11-06 09:36 UTC, jasonhp commented
> It looks good! Although, in its current state, clai wont be able to instanciate the Novita struct. There's two steps missing:
> 
> 1. [Here](https://github.com/baalimago/clai/blob/main/internal/create_queriers.go#L22) the default Novita querier needs to be created. This is what defines the type of the generic `models.Querier` interface, it also ensures that the custom configuration is created for the vendor + that the custom configurations for the specific models gets properly overwritten.
> 2. [Here](https://github.com/baalimago/clai/blob/main/internal/text/querier_setup.go#L20) the vendor, model and model version needs to be parsed, also for the configuration system to work.
> 
> See how `ollama` is setup here for both steps. I'm thinking prefix `novita:` will work well.
> 
> So, if this is done right, I'm thinking it should be possible to run: `clai -cm 'novita:gryphe/mythomax-l2-13b' query example123`

Fixed and tested.

2024-11-06 14:15 UTC, baalimago approved these changes
Looks good and works well! 

I couldn't get tooling to work, but by looking at the API docs, I'm not sure if the Novita API supports this yet?

 Either way, it's an excellent start. Many thanks for the PR and contributions!

2024-11-06 14:15 UTC, baalimago commented on README.md
> +- **Novita AI:**(Optional) Set the `NOVITA_API_KEY` env var to your [Novita API key](https://novita.ai/settings?utm_source=github_clai&utm_medium=github_readme&utm_campaign=link#key-management). [Tex
I'll move this up so that it's after the Ollama in the readme post-merge

2024-11-06 14:18 UTC, merged

2024-11-06 15:50 UTC, jasonhp commented
> Looks good and works well!
> 
> I couldn't get tooling to work, but by looking at the API docs, I'm not sure if the Novita API supports this yet?
> 
> Either way, it's an excellent start. Many thanks for the PR and contributions!

Novita AI does not support tool calling yet.